
import java.awt.datatransfer.Clipboard;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satyam
 */
public class MyNotepad extends javax.swing.JFrame {
    String programName="Notepad";
    String filename="";
    String holdText;
    String fn;
    String dir;
    boolean textChanged=false;
    Clipboard clip=getToolkit().getSystemClipboard();
    /**
     * Creates new form MyNotepad
     */
    public MyNotepad() {
        initComponents();
    }
    
    public void checkFile(){
        BufferedReader read;
        StringBuffer sb=new StringBuffer();
        try{
            read =new BufferedReader(new FileReader);
            String line;
            while((line=read.readLine())!=null)
            {
                sb.append(line+"\n");
            }
            textArea.setText(sb.toString());
            read.close();
        }
        catch (FileNotFoundException e){
            System.out.println("File not found");
        }
        catch (IOException ioe){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        JNewMenu = new javax.swing.JMenuItem();
        jSaveMenu = new javax.swing.JMenuItem();
        jSavAsMenu = new javax.swing.JMenuItem();
        jOpenMenu = new javax.swing.JMenuItem();
        jExitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jColorMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAreaActionPerformed(evt);
            }
        });

        jFile.setText("File");

        JNewMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        JNewMenu.setText("New");
        JNewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNewMenuActionPerformed(evt);
            }
        });
        jFile.add(JNewMenu);

        jSaveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSaveMenu.setText("Save");
        jSaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveMenuActionPerformed(evt);
            }
        });
        jFile.add(jSaveMenu);

        jSavAsMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jSavAsMenu.setText("Save As");
        jSavAsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSavAsMenuActionPerformed(evt);
            }
        });
        jFile.add(jSavAsMenu);

        jOpenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jOpenMenu.setText("Open");
        jFile.add(jOpenMenu);

        jExitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jExitMenu.setText("Exit");
        jFile.add(jExitMenu);

        jMenuBar1.add(jFile);

        jMenu2.setText("Edit");

        jColorMenu.setText("Text Color");
        jMenu2.add(jColorMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaActionPerformed

    private void jSaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaveMenuActionPerformed

    private void jSavAsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSavAsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSavAsMenuActionPerformed

    private void JNewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNewMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JNewMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JNewMenu;
    private javax.swing.JMenuItem jColorMenu;
    private javax.swing.JMenuItem jExitMenu;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jOpenMenu;
    private javax.swing.JMenuItem jSavAsMenu;
    private javax.swing.JMenuItem jSaveMenu;
    private javax.swing.JTextField textArea;
    // End of variables declaration//GEN-END:variables
}
